### ISSUE TITLE
Wrong weights in run code instructions

### ISSUE THREAD

**Issue by MattGrossi-NOAA** [MattGrossi-NOAA/FATES-ATI-FishTracking#1]
The "How to run code" code block in the README file points to yolov5s.pt, but this file does not exist in the repo. Need to correct the code block or provide this file.

**Comment by chiran7** [comment]
Thank you. I will upload the weight.

**Comment by MattGrossi-NOAA** [comment]
from @chiran7: "It is based on yolov8 (not on yolov5). Using pre trained weight of yolov8 may be good. I have updated the readme file replacing the yolov5s.pt."
